// <auto-generated />
namespace Steam.Jogos.Dados.Entity.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.4")]
    public sealed partial class CommitInicial : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(CommitInicial));
        
        string IMigrationMetadata.Id
        {
            get { return "202009250027509_CommitInicial"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
